services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./migration:/docker-entrypoint-initdb.d

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "3001:3001"
  
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
        - "5173:5173"

volumes: 
  pgdata: